const employees = [
    {
      "first_name": "ช่างไฟ",
      "last_name": "ชำนาญ",
      "phone_number": "0111111",
      "birth_date": "10MAR2000",
      "education_id": 0,
      "talent": "NULL",
      "etc": "NULL",
      "email": "changfi.c@gmail.com",
      "id_line": "changfi.c",
      "facebook": "NULL",
      "profile_pic": "NULL",
      "id_card_pic": "NULL",
      "address": "123",
      "country": "ประเทศไทย",
      "province": "กรุงเทพมหานคร",
      "subdistrict": "บางซื่อ",
      "postcode": "11000",
      "start_date": "2021-01-03T14:03:39.000Z",
      "salary": 0,
      "super_id": "NULL",
      "created_at": "2021-01-03T14:03:39.000Z",
      "employee_id": "12345",
      "educationId": 0,
      "departmentId": 0,
      "roleId": 0,
      "employmentId": 0,
      "employement_id": 0
    },
    {
      "first_name": "ช่างเล็ก",
      "last_name": "ชำนาญ",
      "phone_number": "0111112",
      "birth_date": "10MAR2002",
      "education_id": 0,
      "talent": "NULL",
      "etc": "NULL",
      "email": "changfi.c@gmail.com",
      "id_line": "changfi.c",
      "facebook": "NULL",
      "profile_pic": "NULL",
      "id_card_pic": "NULL",
      "address": "123",
      "country": "ประเทศไทย",
      "province": "กรุงเทพมหานคร",
      "subdistrict": "บางซื่อ",
      "postcode": "11000",
      "start_date": "2021-01-03T14:03:39.000Z",
      "salary": 0,
      "super_id": "NULL",
      "created_at": "2021-01-03T14:03:39.000Z",
      "employee_id": "12346",
      "educationId": 0,
      "departmentId": 0,
      "roleId": 1,
      "employmentId": 0,
      "employement_id": 0
    }
  ]

  console.log(employees[0].roleId)